/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logic.RandomStringGenerator;
import logic.ShowMessageCustom;
import logic.Validate;
import model.Voucher;
import repository.repo_voucher;

/**
 *
 * @author Ca1
 */
public class MenuVoucher extends javax.swing.JFrame {

    TableRowSorter<TableModel> sorterSearch;
    DefaultTableModel model = null;
    ArrayList<Voucher> vouchers = null;
    repo_voucher repo_voucher = new repo_voucher();

    /**
     * Creates new form voucher
     */
    public MenuVoucher() {
        initComponents();
        model = (DefaultTableModel) tblVoucher.getModel();
        sorterSearch = new TableRowSorter<>(model);
        tblVoucher.setRowSorter(sorterSearch);
        
        rdConHang.setSelected(true);
        loadListVoucherToTable();
        
        ArrayList<String> cboxSearchItems = getColumnNameVoucher();
        for (String i : cboxSearchItems) {
            cboxSearchVoucher.addItem(i);
        }
    }

    public void loadListVoucherToTable() {
        vouchers = repo_voucher.getListVoucherFromDb();
        model.setRowCount(0);
        for (Voucher i : vouchers) {
            String trangThai;
            switch (i.getTrangThai()) {
                case 0:
                    trangThai = "Hết hàng";
                    break;
                case 1:
                    trangThai = "Còn hàng";
                    break;
                default:
                    throw new AssertionError();
            };
            if (rdConHang.isSelected() && i.getTrangThai() == 1) {
                model.addRow(new Object[]{
                    i.getMaVoucher(), i.getTenVoucher(), i.getSoLuongVoucher(), i.getGioiHanGiamToiThieu(), i.getGioiHanGiamToiDa(), i.getNgayBatDau(), i.getNgayKetThuc(), i.getHinhThucGiam(), trangThai});

            } else if (rdHetHang.isSelected() && i.getTrangThai() == 0) {

                model.addRow(new Object[]{
                    i.getMaVoucher(), i.getTenVoucher(), i.getSoLuongVoucher(), i.getGioiHanGiamToiThieu(), i.getGioiHanGiamToiDa(), i.getNgayBatDau(), i.getNgayKetThuc(), i.getHinhThucGiam(), trangThai});

            }

        }
    }

    public ArrayList<String> getColumnNameVoucher() {
        TableColumnModel columnModel = tblVoucher.getColumnModel();
        ArrayList<String> columnNames = new ArrayList<>();
        for (int i = 0; i < 7; i++) {
            String columnName = columnModel.getColumn(i).getHeaderValue().toString();
            columnNames.add(columnName);
        }
        return columnNames;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        btnXoaVoucher = new javax.swing.JButton();
        btnThemVoucher = new javax.swing.JButton();
        btnSuaVoucher = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTenVoucher = new javax.swing.JTextField();
        txtHinhThucGiam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGioiHanGiamToiDa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGioiHanGiamToiThieu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTimeBeginSale = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTimeEndSale = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rdConHang = new javax.swing.JRadioButton();
        rdHetHang = new javax.swing.JRadioButton();
        txtSearchVoucher = new javax.swing.JTextField();
        cboxSearchVoucher = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khuyến vãi", "Tên voucher", "Số lượng", "Giới hạn giảm tối thiểu", "Giới hạn giảm tối đa", "Ngày bắt đầu", "Ngày kết thúc", "Hình thức giảm", "Trạng thái"
            }
        ));
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVoucher);

        btnXoaVoucher.setBackground(new java.awt.Color(0, 255, 255));
        btnXoaVoucher.setText("Xóa voucher");
        btnXoaVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaVoucherActionPerformed(evt);
            }
        });

        btnThemVoucher.setBackground(new java.awt.Color(0, 255, 255));
        btnThemVoucher.setText("Thêm voucher");
        btnThemVoucher.setBorderPainted(false);
        btnThemVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVoucherActionPerformed(evt);
            }
        });

        btnSuaVoucher.setBackground(new java.awt.Color(0, 255, 255));
        btnSuaVoucher.setText("Sửa voucher");
        btnSuaVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaVoucherActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 255, 255));
        btnReset.setText("Làm mới");

        jLabel1.setText("Tên voucher");

        jLabel2.setText("Hình thức giảm");

        jLabel4.setText("Giới hạn giảm tối đa");

        jLabel3.setText("Giới hạn giảm tối thiếu");

        jLabel5.setText("Thời gian bắt đầu ");

        jLabel6.setText("Thời gian kết thúc");

        jLabel7.setText("Số lượng");

        buttonGroup1.add(rdConHang);
        rdConHang.setText("Còn hàng");
        rdConHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdConHangActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdHetHang);
        rdHetHang.setText("Hết hàng");
        rdHetHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdHetHangActionPerformed(evt);
            }
        });

        txtSearchVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchVoucherActionPerformed(evt);
            }
        });

        cboxSearchVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxSearchVoucherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGioiHanGiamToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHinhThucGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTimeBeginSale, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSuaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGioiHanGiamToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimeEndSale, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cboxSearchVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdConHang)
                        .addGap(18, 18, 18)
                        .addComponent(rdHetHang)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGioiHanGiamToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtTimeBeginSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtHinhThucGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txtGioiHanGiamToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(txtTimeEndSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdConHang)
                    .addComponent(rdHetHang)
                    .addComponent(txtSearchVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxSearchVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimeBeginSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeBeginSaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeBeginSaleActionPerformed

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
        int index = tblVoucher.getSelectedRow();
        Voucher voucher = vouchers.get(index);

        txtTenVoucher.setText(voucher.getTenVoucher());
        txtHinhThucGiam.setText(voucher.getHinhThucGiam());
        txtGioiHanGiamToiDa.setText(voucher.getGioiHanGiamToiDa() + "");
        txtGioiHanGiamToiThieu.setText(voucher.getGioiHanGiamToiThieu() + "");
        txtTimeBeginSale.setText(voucher.getNgayBatDau());
        txtTimeEndSale.setText(voucher.getNgayKetThuc());
        txtSoLuong.setText(voucher.getSoLuongVoucher() + "");
    }//GEN-LAST:event_tblVoucherMouseClicked

    private Validate check() {
        Validate validate = new Validate();
        validate.checkNull("Tên voucher", txtTenVoucher.getText());
        validate.checkNull("Hình thức giảm", txtHinhThucGiam.getText());
        validate.checkNull("Số lượng", txtSoLuong.getText());
        validate.checkNumber("Số lượng", txtSoLuong.getText());
        validate.checkNull("Giới hạn giảm tối thiểu", txtGioiHanGiamToiThieu.getText());
        validate.checkNumber("Giới hạn giảm tối thiểu", txtGioiHanGiamToiThieu.getText());
        validate.checkNull("Giới hạn giảm tối đa", txtGioiHanGiamToiDa.getText());
        validate.checkNumber("Giới hạn giảm tối đa", txtGioiHanGiamToiDa.getText());
        validate.checkNull("Thời gian bắt đầu", txtTimeBeginSale.getText());
        validate.checkNull("Thời gian bắt đầu", txtTimeEndSale.getText());
        return validate;
    }
    private void btnThemVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVoucherActionPerformed
        Validate validate = check();
        if (validate.isChuoiHopLe()) {
            Voucher voucher = getNewVoucherFromForm();
            repo_voucher.addVoucherToDB(voucher);
            loadListVoucherToTable();
        } else {
            validate.showWarning(this);
        }
    }//GEN-LAST:event_btnThemVoucherActionPerformed

    private Voucher getNewVoucherFromForm() {
        Voucher voucher = new Voucher(
                RandomStringGenerator.generateRandomString("VC"), // maVoucher
                txtTenVoucher.getText(), // tenVoucher
                txtHinhThucGiam.getText(), // hinhThucGiam
                Integer.parseInt(txtSoLuong.getText()), // soLuongVoucher
                1, // trangThai
                Double.parseDouble(txtGioiHanGiamToiThieu.getText()), // gioiHanGiamToiThieu
                Double.parseDouble(txtGioiHanGiamToiDa.getText()), // gioiHanGiamToiDa
                txtTimeBeginSale.getText(), // ngayBatDau
                txtTimeEndSale.getText() // ngayKetThuc
        );
        return voucher;
    }


    private void btnSuaVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaVoucherActionPerformed
        int index = tblVoucher.getSelectedRow();
        if (index == -1) {
            ShowMessageCustom.showMessageWarning(this, "Vui lòng chọn dòng muốn sửa");
        } else {
            Validate validate = check();
            if (validate.isChuoiHopLe()) {
                Voucher voucher = getNewVoucherFromForm();
                String maVoucher = tblVoucher.getValueAt(index, 0).toString();
                voucher.setMaVoucher(maVoucher);
                repo_voucher.updateVoucherToDb(voucher);
                loadListVoucherToTable();
                ShowMessageCustom.showMessageSuccess(this, "Update thành công");
            } else {
                validate.showWarning(this);
            }
        }
    }//GEN-LAST:event_btnSuaVoucherActionPerformed

    private void rdConHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdConHangActionPerformed
        loadListVoucherToTable();
    }//GEN-LAST:event_rdConHangActionPerformed

    private void rdHetHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdHetHangActionPerformed
        loadListVoucherToTable();
    }//GEN-LAST:event_rdHetHangActionPerformed

    private void btnXoaVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaVoucherActionPerformed
        int index = tblVoucher.getSelectedRow();
        if (index == -1) {
            ShowMessageCustom.showMessageWarning(this, "Vui lòng chọn dòng muốn xóa");
        } else {
            String maVoucher = tblVoucher.getValueAt(index, 0).toString();
            repo_voucher.removeVoucherToDb(maVoucher);
            loadListVoucherToTable();
            ShowMessageCustom.showMessageSuccess(this, "Remove thành công");
        }
    }//GEN-LAST:event_btnXoaVoucherActionPerformed

    private void cboxSearchVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxSearchVoucherActionPerformed
        txtSearchVoucher.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                search(txtSearchVoucher.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                search(txtSearchVoucher.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                search(txtSearchVoucher.getText());
            }

            private void search(String text) {
                int columnIndex = cboxSearchVoucher.getSelectedIndex();
                sorterSearch.setRowFilter(RowFilter.regexFilter("(?i)" + text, columnIndex));
            }
        });
    }//GEN-LAST:event_cboxSearchVoucherActionPerformed

    private void txtSearchVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchVoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchVoucherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVoucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSuaVoucher;
    private javax.swing.JButton btnThemVoucher;
    private javax.swing.JButton btnXoaVoucher;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboxSearchVoucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdConHang;
    private javax.swing.JRadioButton rdHetHang;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTextField txtGioiHanGiamToiDa;
    private javax.swing.JTextField txtGioiHanGiamToiThieu;
    private javax.swing.JTextField txtHinhThucGiam;
    private javax.swing.JTextField txtSearchVoucher;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenVoucher;
    private javax.swing.JTextField txtTimeBeginSale;
    private javax.swing.JTextField txtTimeEndSale;
    // End of variables declaration//GEN-END:variables
}
